services:
  jenkins:
    build:
      context: ./jenkins-image
      dockerfile: Dockerfile
    container_name: jenkins
    restart: on-failure
    privileged: true
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      DOCKER_TLS_CERT_DIR: /certs
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    networks:
      - jenkins-docker
    volumes:
      - ./certs:/certs/client:ro
      - ./data:/var/jenkins_home
  docker:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: docker
    ports:
      - "2376:2376"
    environment:
      DOCKER_TLS_CERT_DIR: /certs
    networks:
      - jenkins-docker
    privileged: true
    volumes:
      - ./certs:/certs/client
      - ./data:/var/jenkins_home

networks:
  jenkins-docker:
    driver: bridge